# Generated by Django 5.0.6 on 2024-06-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('beacon_id', models.AutoField(primary_key=True, serialize=False)),
                ('transmit_power', models.FloatField()),
                ('coordinates', models.JSONField()),
                ('floor', models.IntegerField()),
                ('time_spent', models.JSONField(default=dict)),
                ('enter_time', models.JSONField(default=dict)),
                ('exit_time', models.JSONField(default=dict)),
                ('user_time', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('path', models.JSONField(default=list)),
                ('estimated_path', models.JSONField(default=list)),
                ('time_spent', models.JSONField(default=dict)),
            ],
        ),
    ]
