# Generated by Django 5.0.6 on 2024-09-26 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_user_step_pointer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='step_pointer',
        ),
        migrations.AddField(
            model_name='user',
            name='first_step',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 19, 41, 3, 983573)),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 19, 41, 3, 983573)),
        ),
    ]
