# Generated by Django 5.0.6 on 2024-09-27 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_user_step_pointer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_step',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
