# Generated by Django 5.0.6 on 2024-09-26 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_remove_user_path_remove_user_step_pointer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_step',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
